### ISSUE TITLE
pls don't erase solutions in progress

### ISSUE THREAD

**Issue by andrew-buchanan** [dturevski/olive-gui#36]
Hi when I am solving a problem, it can take some time.

If I go away to another window, then come back to Olive, then it's cool - progress so far is displayed

However,
(1)  I go to another diagram in olive and return to the one which is running, then the work in progress is gone!

(2) Also if I scroll up and down in the wip, then any new stuff added can be inserted in the middle of the solution text already posted.

(3) Also, can solution text be added persistently to the end of whatever solutions are already in the solutions tab (kind of like what popeye does be default when run standalone)

Thanks so much

**Comment by dturevski** [comment]
(1) I think you have already requested this feature and it was implemented in 1.3: #22
Also it is often much more handy to start several instances of Olive and switch between them, rather than switch between the entries in a single instance. 
(2) Yeah, I see how that could be happening. The output window is read-only, but you can still move the cursor by clicking around (scrolling should not have an effect). I'll see if that's fixable.
(3) No, that is not the point of the solutions tab. Perhaps, what you need is the communication log that was also implemented after your request? #21

**Comment by dturevski** [comment]
(2) fixed in 1.5
